Fix States
nasa/prog_models pull request #125
Opened 2021-08-13 23:44 UTC by teubert

* Add description for states
* Add additional state limits

2021-08-13 23:47 UTC, teubert commented
@chetankul : Could you take a look at this and see 1. is the description I added accurate, 2. Fill in the description for the missing 2 circuit states, 3. Confirm the limits I set for the states, and 4. See if I missed any limits

2021-08-19 23:36 UTC, chetankul commented on src/prog_models/models/battery_circuit.py
> +        | qcp :
qb : charge stored in Capacitor Cb of the equivalent circuit model
qcp : charge stored in Capacitor Ccp of the equivalent circuit model
qcs : charge stored in Capacitor Ccs of the equivalent circuit model

2021-08-19 23:38 UTC, chetankul approved these changes

2021-08-19 23:40 UTC, chetankul requested changes
qb : charge stored in Capacitor Cb of the equivalent circuit model
qcp : charge stored in Capacitor Ccp of the equivalent circuit model
qcs : charge stored in Capacitor Ccs of the equivalent circuit model

2021-08-19 23:59 UTC, chetankul requested changes
since thermal runaways starts above 130C could we update the limits for tb to (-273.15, 423.15).
Rest of the limits and values look good to me

2021-08-20 14:24 UTC, merged