Implement Linear Model
nasa/prog_models pull request #179
Opened 2021-12-23 17:57 UTC by teubert

Implement a linear model abstract base class for models that can be described as a linear timeseries. Created an example demonstrating this

2022-01-04 15:15 UTC, teubert commented
Note: Should fail on released version of prog_algs, but pass on dev

2022-01-12 23:04 UTC, matteocorbetta commented on src/prog_models/linear_model.py
> +        * dx/dt = Ax + Bu + C
Notation: typical notation is sligthly different. I'd recommend following the standard one, and I can rewrite LinearModel accordingly.

dx/dt = Ax + Bu + E
y = Cx + D
es = Fx + G

2022-01-12 23:07 UTC, matteocorbetta commented on src/prog_models/linear_model.py
> +        * A: 2-d numpy.array[float]
We could add matrix dimensions; makes life easier for the user

A -> n_states x n_states
B -> n_states x n_inputs
E -> n_states x n_state_disturbances 

C -> n_outputs x n_states
D -> n_outputs x n_meas_disturbances

F -> n_eventstates x n_states
G -> n_eventstates x n_es_disturbances

2022-01-12 23:50 UTC, matteocorbetta requested changes
Requesting changing on matrix notations (files edited) before merging.

2022-01-12 23:55 UTC, matteocorbetta approved these changes

2022-01-13 15:11 UTC, merged