Feature for simulate_to* to return namedtuples instead of basic tuples
nasa/prog_models pull request #208
Opened 2022-02-14 20:03 UTC by lawrence-hwang

Implementing change for simulate_to* methods in prog_models/prognostics_model.py to return namedtuples instead of basic tuples. Motivation for change is ease of readability and access to objects in the return from the method's result.

2022-02-15 22:05 UTC, teubert requested changes
Wow, this worked out really cleanly. Great work. 

Could you also look at the examples and make changes to a few or all of them to use the named tuple notation?

2022-02-15 22:05 UTC, teubert commented on tests/test_battery.py
> +from pandas import array
```suggestion
```

I think this was accidental.

2022-02-16 06:47 UTC, lawrence-hwang commented
> Wow, this worked out really cleanly. Great work.
> 
> Could you also look at the examples and make changes to a few or all of them to use the named tuple notation?

namedtuple Notation applied to only a few of the examples:
    - Call simulate_to just to call, don’t unpack returned items for separate use (no changes applied):
        - benchmarking, dynamic_step_size, simulate_to_threshold, sim_battery_eol, sim_valve, sim, vectorized
    - Don’t use simulate_to at all (no changes applied):
        - derived_params, param_est
    - Examples switched to Namedtuple syntax (changes applied):
        - events,  future_loading, model_gen, new_model (unpacking names changed), noise, sensitivity, sim_pump, state_limits, visualize

2022-02-16 19:19 UTC, teubert approved these changes

2022-02-16 19:20 UTC, merged