Tests/move linear model
nasa/prog_models pull request #489
Opened 2023-02-01 21:18 UTC by aqitya

Improvements to linear_model_tests. Moved linear model tests from test_base_models to a separate file. This PR takes a step towards implementing a fix for #191.

2023-02-02 02:24 UTC, teubert requested changes
Great update that will set the stage for future expansion of the linear model tests. 

A few small suggestions- one to fix the issue with the automated tests, and the second to clean up unused imports

Great work!

2023-02-02 02:24 UTC, teubert commented on tests/test_linear_model.py
> +from prog_models import *
```suggestion
```
Looking through the code, I don't think that line is needed

2023-02-02 17:56 UTC, aqitya commented on tests/test_linear_model.py
> +from test_base_models import LinearThrownObject
Yep, makes sense. Will do the corresponding changes promptly.

2023-02-02 21:47 UTC, teubert approved these changes
Looks good- good work. 

One last comment: I suggest you remove LinearThrownObject from test_base_models as well, and replace it with an import from test_models.linear_thrown_object

2023-02-03 01:39 UTC, kjjarvis approved these changes
Good start to improving linear_tests. New formatting looks good

2023-02-04 00:38 UTC, merged