Updated containers with organized comments.
nasa/prog_models pull request #495
Opened 2023-02-14 02:48 UTC by mstraut

2023-02-14 21:53 UTC, mstraut reviewed
all comments are now placed properly

2023-02-24 22:50 UTC, mstraut reviewed
moved some comments, and updated import

2023-03-03 01:07 UTC, teubert commented on src/prog_models/utils/containers.py
> +        Arguments:
For the sphinx doc generation to work correctly, the arguments for the constructor need to be in the doc comments for the class. You can repeat it here if you feel it helps, but add it back to the doc comment above. 

Also, note that doc comments need to be in numpy or google format for sphinx doc generation to work. 

* Numpy: https://numpydoc.readthedocs.io/en/latest/format.html or https://python.plainenglish.io/how-to-write-numpy-style-docstrings-a092121403ba
* Google: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2023-03-03 01:08 UTC, teubert requested changes
All these comments are helpful. Once the constructor doc comment is fixed I'm ready to approve. 

Thanks!

2023-03-14 23:05 UTC, teubert commented on src/prog_models/utils/containers.py
> +        return self.matrix_check    #he matrix (vectorized case)
```suggestion
        return self.matrix    # the matrix (vectorized case)
```

I think this is supposed to be self.matrix. I think this is why the tests are failing

2023-03-14 23:06 UTC, teubert approved these changes
Can be merged after the typo in values is fixed and tests pass.

Great improvements to documentation and readability of containers

2023-03-21 01:31 UTC, merged