Pneumatic Valve Split
nasa/prog_models pull request #74
Opened 2021-07-15 17:07 UTC by wlamberson1

Split PneumaticValve model into PneumaticValveBase and PneumaticValveWithWear (like pump model).  Updated tests to reflect changes.

2021-07-15 17:54 UTC, jason-watkins approved these changes

2021-07-15 19:41 UTC, teubert approved these changes

2021-07-15 19:42 UTC, teubert commented
Looks good. Good work!

2021-07-15 19:43 UTC, teubert requested changes
Actually just caught something. Make sure you remove the apply_noise calls from within the class (since they're now done in the private classes)

2021-07-17 18:10 UTC, teubert approved these changes
Approve- we're opening up a separate issue to remove the apply_noise functions from every model

2021-07-17 18:44 UTC, merged