Individual Test Execution
nasa/prog_models pull request #79
Opened 2021-07-22 18:53 UTC by wlamberson1

Add ability to execute tests individually

2021-07-22 19:01 UTC, jason-watkins approved these changes

2021-07-22 23:27 UTC, teubert requested changes
Looks good except for the comments- I made some suggestions to make them a little clearer

2021-07-22 23:27 UTC, teubert commented on tests/test_base_models.py
> +    # This makes sure that you are in the correct directory
```suggestion
    # This ensures that the directory containing ProgModelTemplate is in the python search directory
```

2021-07-22 23:27 UTC, teubert commented on tests/test_examples.py
> +# This makes sure that you are in the correct directory
```suggestion
# This ensures that the directory containing examples is in the python search directories 
```

2021-07-23 14:23 UTC, teubert approved these changes

2021-07-23 23:06 UTC, merged